// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQI__a7fbUuF9CX1ZI8ldTD6nd_dvXWI',
    appId: '1:82658166126:web:03f7baf850306351992d7f',
    messagingSenderId: '82658166126',
    projectId: 'proapp-85d2d',
    authDomain: 'proapp-85d2d.firebaseapp.com',
    storageBucket: 'proapp-85d2d.firebasestorage.app',
    measurementId: 'G-HEDXL7XENT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkb80W61-BMvu4o4DtrsADN4qL_7zjhdc',
    appId: '1:82658166126:android:67a5906a36300c58992d7f',
    messagingSenderId: '82658166126',
    projectId: 'proapp-85d2d',
    storageBucket: 'proapp-85d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQC5LURJE7rQ3jdF8PVcpXUofcBYe1HQ8',
    appId: '1:82658166126:ios:b0f406f99c1c28a9992d7f',
    messagingSenderId: '82658166126',
    projectId: 'proapp-85d2d',
    storageBucket: 'proapp-85d2d.firebasestorage.app',
    iosBundleId: 'com.app.proapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQC5LURJE7rQ3jdF8PVcpXUofcBYe1HQ8',
    appId: '1:82658166126:ios:b0f406f99c1c28a9992d7f',
    messagingSenderId: '82658166126',
    projectId: 'proapp-85d2d',
    storageBucket: 'proapp-85d2d.firebasestorage.app',
    iosBundleId: 'com.app.proapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQI__a7fbUuF9CX1ZI8ldTD6nd_dvXWI',
    appId: '1:82658166126:web:72ec291df05e7e61992d7f',
    messagingSenderId: '82658166126',
    projectId: 'proapp-85d2d',
    authDomain: 'proapp-85d2d.firebaseapp.com',
    storageBucket: 'proapp-85d2d.firebasestorage.app',
    measurementId: 'G-FRHGVYMWEG',
  );
}
